#lang racket
(require "parenlog.rkt")

(define-model family-tree
    (parent rogue moria)
    (parent rogue larn)
    (parent rogue omega)
    (parent rogue hack)
    (parent moria angband)
    (parent hack nethack)
    (parent angband tome)
    (parent angband zangband)
    (parent omega adom)
    (parent nethack adom)
    (parent nethack zapm)
    (parent nethack slashem)
    (parent nethack crawl)
    (:- (sibling X Y)
        (parent Z X)
        (parent Z Y)
        (,(compose not equal?) X Y)))
;(query-model family-tree (sibling X Y))